name: 'Telemetry'
on:
  pull_request:
    paths:
      - 'src/client/telemetry/*.ts'
  push:
    branches-ignore:
      - 'main'
      - 'release*'
    paths:
      - 'src/client/telemetry/*.ts'

jobs:
  check-metdata:
    name: 'Check metadata'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3.1.0'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'

      - name: 'Run vscode-telemetry-extractor'
        run: 'npx --package=@vscode/telemetry-extractor --yes vscode-telemetry-extractor -s src/client/telemetry/'
